runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /favicon\.ico
  static_files: img/favicon\.ico
  upload: img/favicon\.ico
- url: /.*
  script: _go_app
  secure: always
  redirect_http_response_code: 301
