runtime: go112
# https://cloud.google.com/appengine/docs/standard/go112/go-differences
# default value is 10m
# default_expiration: "10m"

handlers:
  - url: /css
    static_dir: css
    # expiration: "10m"
  - url: /js
    static_dir: js
    # expiration: "10m"
  - url: /img
    static_dir: img
    expiration: "10d"
  - url: /favicon\.ico
    static_files: img/favicon\.ico
    upload: img/favicon\.ico
    # expiration: "10m"
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
